## Top 30

In [244]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Alice", "Bob", "Charlie", "David", "Eva",
             "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance"],
    "age": [25, 32, 28, 45, 29, 35, 41, 26, np.nan, 38],
    "salary": [60000, 52000, 75000, 90000, 58000,
               72000, 85000, np.nan, 62000, 95000],
    "experience": [2, 8, 4, 18, 5, 10, 15, 3, 6, 12],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
             "Delhi", "Pune", "Delhi", "Mumbai", "Delhi"],
    "joining_date": [
        "2022-01-15", "2018-03-10", "2021-06-20", "2006-07-01",
        "2020-02-15", "2016-11-10", "2009-05-20", "2023-01-05",
        "2019-08-12", "2014-04-25"
    ],
    "performance_score": [8.5, 7.2, 9.1, 8.8, 6.9,
                          9.5, 7.8, 8.2, np.nan, 9.0]
})

df["joining_date"] = pd.to_datetime(df["joining_date"])

In [3]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [4]:
df[["name","department","salary"]]

      name department   salary
0    Alice         IT  60000.0
1      Bob         HR  52000.0
2  Charlie         IT  75000.0
3    David    Finance  90000.0
4      Eva         HR  58000.0
5    Frank         IT  72000.0
6    Grace    Finance  85000.0
7    Henry         IT      NaN
8      Ivy         HR  62000.0
9     Jack    Finance  95000.0

In [ ]:
df[df["salary"]>7000]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [7]:
df[(df["salary"]>7000) & (df["department"] == "IT")]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5

In [11]:
df.loc[2:5][["name","salary"]]

      name   salary
2  Charlie  75000.0
3    David  90000.0
4      Eva  58000.0
5    Frank  72000.0

In [15]:
df.iloc[2:6,1:4]

      name department   age
2  Charlie         IT  28.0
3    David    Finance  45.0
4      Eva         HR  29.0
5    Frank         IT  35.0

In [16]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [17]:
df.sort_values("salary",ascending=False)

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2

In [19]:
df.sort_values(["department","salary"], ascending=[False,True])

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [20]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [26]:
df.isna().sum()

employee_id          0
name                 0
department           0
age                  1
salary               1
experience           0
city                 0
joining_date         0
performance_score    1
dtype: int64

In [31]:
df["salary"] = df["salary"].fillna(df["salary"].mean()).round(1)

In [34]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [37]:
df.dropna(subset="salary")

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [46]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0

In [52]:
df.groupby("department")["salary"].mean().round(2)

department
Finance    90000.00
HR         57333.33
IT         69000.00
Name: salary, dtype: float64

In [61]:
df.groupby("department").agg(
    average_Salary = ("salary", "mean"),
    count_emp =("salary", "count"),
    max_salary = ("salary", "max")
)

            average_Salary  count_emp  max_salary
department
Finance       90000.000000          3     95000.0
HR            57333.333333          3     62000.0
IT            69000.000000          3     75000.0

In [62]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0

In [63]:
df.groupby("city").agg(
    avg_salary = ("salary", "mean"),
    min_salary=("salary", "min"),
    max_salary=("salary", "max"),
    avg_exp=("experience", "mean")


)

          avg_salary  min_salary  max_salary    avg_exp
city
Delhi   75500.000000     60000.0     95000.0   6.200000
Mumbai  57333.333333     52000.0     62000.0   6.333333
Pune    87500.000000     85000.0     90000.0  16.500000

In [80]:
# df.groupby("department")["employee_id"].count()
# total = df.count()
df["department"].value_counts(normalize=True)*100

department
IT         40.0
HR         30.0
Finance    30.0
Name: proportion, dtype: float64

In [81]:
df["salary_in_lakhs"] = df["salary"]/ 100000

In [82]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95

In [83]:
df["senior"] = df["experience"]>=10

In [84]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True

In [99]:
import numpy as np


df["salary_level"] = np.where(
                                df["salary"] > 80000,
                                "High",
                                "Normal"
                                         )


df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High

In [102]:
df["age_cat"] = df["age"].apply(
    lambda x: "Young" if x < 30 else "Experienced"
)

In [103]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced

In [105]:
df[df["name"].str.startswith("A")]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.6,False,Normal,Young

In [108]:
df[df["city"].str.contains("Delhi")]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced

In [109]:
df["name"].str.upper()

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4        EVA
5      FRANK
6      GRACE
7      HENRY
8        IVY
9       JACK
Name: name, dtype: str

In [110]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced

### Date operations

##### joining Yearly

In [113]:
df["joining_yearly"] = df["joining_date"].dt.year
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014

In [123]:
df["month"]= df["joining_date"].dt.month

In [124]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

In [119]:
df[df["joining_yearly"] > 2020]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1

In [125]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

## find Duplicate

In [132]:
df[df.duplicated("city")]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

In [133]:
df.drop_duplicates("employee_id")

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

In [137]:
df.rename(
    columns={
    "employee_id":"id",
    "performance_score":"performance"
})

,id,name,department,age,salary,experience,city,joining_date,performance,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

In [138]:
dept = pd.DataFrame({
    "department": ["IT", "HR", "Finance"],
    "manager": ["John", "Sarah", "Mike"]
})

In [140]:
df.merge(
    dept,
    left_on="department",
    right_on="department",
    how="left"


)

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,manager
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1,John
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3,Sarah
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6,John
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7,Mike
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2,Sarah
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,John
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5,Mike
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1,John
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8,Sarah
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,Mike

## Concatination

In [141]:
new_employees = pd.DataFrame({
    "employee_id": [111, 112],
    "name": ["Kate", "Leo"],
    "department": ["IT", "HR"],
    "salary": [70000, 55000]
})

In [142]:
new_employees

   employee_id  name department  salary
0          111  Kate         IT   70000
1          112   Leo         HR   55000

In [144]:
pd.concat([df,new_employees],ignore_index=True)

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2.0,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022.0,1.0
1,102,Bob,HR,32.0,52000.0,8.0,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018.0,3.0
2,103,Charlie,IT,28.0,75000.0,4.0,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021.0,6.0
3,104,David,Finance,45.0,90000.0,18.0,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006.0,7.0
4,105,Eva,HR,29.0,58000.0,5.0,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020.0,2.0
5,106,Frank,IT,35.0,72000.0,10.0,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016.0,11.0
6,107,Grace,Finance,41.0,85000.0,15.0,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009.0,5.0
7,108,Henry,IT,26.0,NaN,3.0,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023.0,1.0
8,109,Ivy,HR,NaN,62000.0,6.0,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019.0,8.0
9,110,Jack,Finance,38.0,95000.0,12.0,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014.0,4.0
10,111,Kate,IT,NaN,70000.0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,112,Leo,HR,NaN,55000.0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

In [155]:
df.sort_values("salary",ascending=False).iloc[0]

employee_id                          110
name                                Jack
department                       Finance
age                                 38.0
salary                           95000.0
experience                            12
city                               Delhi
joining_date         2014-04-25 00:00:00
performance_score                    9.0
salary_1                         95000.0
salary_in_lakhs                     0.95
senior                              True
salary_level                        High
age_cat                      Experienced
joining_yearly                      2014
month                                  4
Name: 9, dtype: object

In [159]:
df.loc[df["salary"].idxmax()]

employee_id                          110
name                                Jack
department                       Finance
age                                 38.0
salary                           95000.0
experience                            12
city                               Delhi
joining_date         2014-04-25 00:00:00
performance_score                    9.0
salary_1                         95000.0
salary_in_lakhs                     0.95
senior                              True
salary_level                        High
age_cat                      Experienced
joining_yearly                      2014
month                                  4
Name: 9, dtype: object

### 3 largest

In [160]:
df.sort_values("salary",ascending=False).head(3)

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5

In [161]:
df.nlargest(3, "salary")

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5

In [162]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4

#### Department Highest Salary

In [169]:
max_sal = df.groupby("department")["salary"].idxmax()

In [171]:
df.loc[max_sal]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6

In [173]:
df.groupby("department").max()

,employee_id,name,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month
department,,,,,,,,,,,,,,,
Finance,110,Jack,45.0,95000.0,18,Pune,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,7
HR,109,Ivy,32.0,62000.0,8,Mumbai,2020-02-15,7.2,62000.0,0.62,False,Normal,Young,2020,8
IT,108,Henry,35.0,75000.0,10,Delhi,2023-01-05,9.5,75000.0,0.75,True,Normal,Young,2023,11

#### Rank()

In [183]:
df["salary_rank"]=df["salary"].sort_values(ascending=False).rank(method = 'first',
        ascending=False)

In [184]:
df.sort_values("salary",ascending=False)

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7,2.0
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5,3.0
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6,4.0
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8,6.0
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1,7.0
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2,8.0
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3,9.0
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1,NaN

In [196]:
df["avg_salary"] = df.groupby("department")["salary"].transform("mean")
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank,avg_salary
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1,7.0,69000.000000
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3,9.0,57333.333333
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6,4.0,69000.000000
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7,2.0,90000.000000
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2,8.0,57333.333333
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0,69000.000000
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5,3.0,90000.000000
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1,NaN,69000.000000
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8,6.0,57333.333333
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0,90000.000000

In [205]:
avg = df.groupby("department")["salary"].transform("mean")

In [207]:
df[df["salary"] > avg ]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank,avg_salary
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6,4.0,69000.000000
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2,8.0,57333.333333
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0,69000.000000
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8,6.0,57333.333333
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0,90000.000000

In [208]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank,avg_salary
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1,7.0,69000.000000
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3,9.0,57333.333333
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6,4.0,69000.000000
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7,2.0,90000.000000
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2,8.0,57333.333333
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0,69000.000000
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5,3.0,90000.000000
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1,NaN,69000.000000
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8,6.0,57333.333333
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0,90000.000000

In [225]:
pd.pivot_table(
    df,
    values= "salary",
    index="department",
    columns="city",
    aggfunc="mean"
)

city          Delhi        Mumbai     Pune
department
Finance     95000.0           NaN  87500.0
HR              NaN  57333.333333      NaN
IT          69000.0           NaN      NaN

In [226]:
df.groupby(["department","city"])["salary"].mean()

department  city
Finance     Delhi     95000.000000
            Pune      87500.000000
HR          Mumbai    57333.333333
IT          Delhi     69000.000000
Name: salary, dtype: float64

In [227]:
scores = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "math": [80, 70, 90],
    "science": [85, 75, 95]
})
scores

      name  math  science
0    Alice    80       85
1      Bob    70       75
2  Charlie    90       95

In [228]:
pd.melt(
    scores,
    id_vars="name",
    var_name="subjects",
    value_name="score")

      name subjects  score
0    Alice     math     80
1      Bob     math     70
2  Charlie     math     90
3    Alice  science     85
4      Bob  science     75
5  Charlie  science     95

In [229]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank,avg_salary
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5,60000.0,0.60,False,Normal,Young,2022,1,7.0,69000.000000
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2,52000.0,0.52,False,Normal,Experienced,2018,3,9.0,57333.333333
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1,75000.0,0.75,False,Normal,Young,2021,6,4.0,69000.000000
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8,90000.0,0.90,True,High,Experienced,2006,7,2.0,90000.000000
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9,58000.0,0.58,False,Normal,Young,2020,2,8.0,57333.333333
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0,69000.000000
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8,85000.0,0.85,True,High,Experienced,2009,5,3.0,90000.000000
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2,NaN,NaN,False,Normal,Young,2023,1,NaN,69000.000000
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN,62000.0,0.62,False,Normal,Experienced,2019,8,6.0,57333.333333
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0,90000.000000

26. Find employees satisfying multiple conditions

Question:

Find employees who:

are in Delhi
have experience > 5
performance score >= 8

In [ ]:
df[ (df["city"] == "Delhi") &
    (df["experience"] > 5) &
    (df["performance_score"] >= 8) ]

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank,avg_salary
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0,69000.0
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0,90000.0

In [232]:
df.query("city == 'Delhi' and  experience >5")

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score,salary_1,salary_in_lakhs,senior,salary_level,age_cat,joining_yearly,month,salary_rank,avg_salary
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5,72000.0,0.72,True,Normal,Experienced,2016,11,5.0,69000.0
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0,95000.0,0.95,True,High,Experienced,2014,4,1.0,90000.0

### 27. Memory optimization ⭐⭐

Interview question:

You have a DataFrame with 50 million rows. How would you reduce memory usage?

In [233]:
chunks  = pd.read_csv("tips.csv",chunksize=10)



for chunk in chunks:
    print(chunk)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2
    total_bill   tip     sex smoker  day    time  size
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
15       21.58  3.92    Male     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3
17       16.29  3.71    Male     No  Sun  Dinner     3
18       16.97  3.50  Female     No  Sun  Dinner     3
19       20.65  3.35    Male     No  Sat  Dinner     3
    total_bill   tip     sex smoker  day    time  size
20       17.92  4.08    Male     No  Sat  Dinner     2
21       20.29  2.75  Female     No  Sat  Dinner     2
22       15.77  2.23  Female     No  Sat  Dinner     2
23       39.42  7.58    Male     No  Sat  Dinner     4
24       19.82  3.18    Male     No  Sat  Dinner     2
25       17.81  2.34    Male     No  Sat  Dinner     4
26       13.37  2.00    Male     No  Sat  Dinner     2
27       12.69  2.00    Male     No  Sat  Dinner     2
28       21.70  4.30    Male     No  Sat  Dinner     2
29       19.65  3.00  Female     No  Sat  Dinner     2
    total_bill   tip     sex smoker  day    time  size
30        9.55  1.45    Male     No  Sat  Dinner     2
31       18.35  2.50    Male     No  Sat  Dinner     4
32       15.06  3.00  Female     No  Sat  Dinner     2
33       20.69  2.45  Female     No  Sat  Dinner     4
34       17.78  3.27    Male     No  Sat  Dinner     2
35       24.06  3.60    Male     No  Sat  Dinner     3
36       16.31  2.00    Male     No  Sat  Dinner     3
37       16.93  3.07  Female     No  Sat  Dinner     3
38       18.69  2.31    Male     No  Sat  Dinner     3
39       31.27  5.00    Male     No  Sat  Dinner     3
    total_bill   tip   sex smoker  day    time  size
40       16.04  2.24  Male     No  Sat  Dinner     3
41       17.46  2.54  Male     No  Sun  Dinner     2
42       13.94  3.06  Male     No  Sun  Dinner     2
43        9.68  1.32  Male     No  Sun  Dinner     2
44       30.40  5.60  Male     No  Sun  Dinner     4
45       18.29  3.00  Male     No  Sun  Dinner     2
46       22.23  5.00  Male     No  Sun  Dinner     2
47       32.40  6.00  Male     No  Sun  Dinner     4
48       28.55  2.05  Male     No  Sun  Dinner     3
49       18.04  3.00  Male     No  Sun  Dinner     2
    total_bill   tip     sex smoker  day    time  size
50       12.54  2.50    Male     No  Sun  Dinner     2
51       10.29  2.60  Female     No  Sun  Dinner     2
52       34.81  5.20  Female     No  Sun  Dinner     4
53        9.94  1.56    Male     No  Sun  Dinner     2
54       25.56  4.34    Male     No  Sun  Dinner     4
55       19.49  3.51    Male     No  Sun  Dinner     2
56       38.01  3.00    Male    Yes  Sat  Dinner     4
57       26.41  1.50  Female     No  Sat  Dinner     2
58       11.24  1.76    Male    Yes  Sat  Dinner     2
59       48.27  6.73    Male     No  Sat  Dinner     4
    total_bill   tip     sex smoker  day    time  size
60       20.29  3.21    Male    Yes  Sat  Dinner     2
61       13.81  2.00    Male    Yes  Sat  Dinner     2
62       11.02  1.98    Male    Yes  Sat  Dinner     2
63       18.29  3.76    Male    Yes  Sat  Dinner     4
64       17.59  2.64    Male     No  Sat  Dinner     3
65       20.08  3.15    Male     No  Sat  Dinner     3
66       16.45  2.47  Female     No  Sat  Dinner     2
67        3.07  1.00  Female    Yes  Sat  Dinner     1
68       20.23  2.01    Male     No  Sat  Dinner     2
69       15.01  2.09    Male    Yes  Sat  Dinner     2
    total_bill   tip     sex smoker   day    time  size
70       12.02  1.97    Male     No   Sat  Dinner     2
71       17.07  3.00  Female     No   Sat  Dinner     3
72       26.86  3.14  Female    Yes   Sat  Dinner     2
73       25.28  5.00  Female    Yes   Sat  Dinner     2
74       14.73  2.20  Female     No   Sat  Dinner     2
75       10.51  1.25    Male     No   Sat  Dinner     2
76       17.92  3.08    Male    Yes   Sat  Dinner     2
77       27.20  4.00    Male     No  Thur   Lunch     4
78       22.76  3.00    Male     No  Thur   Lunch     2
79       17.29  2.71    Male     No  Thur   Lunch     2
    total_bill   tip     sex smoker   day   time  size
80       19.44  3.00    Male    Yes  Thur  Lunch     2
81       16.66  3.40    Male     No  Thur  Lunch     2
82       10.07  1.83  Female     No  Thur  Lunch     1
83       32.68  5.00    Male    Yes  Thur  Lunch     2
84       15.98  2.03    Male     No  Thur  Lunch     2
85       34.83  5.17  Female     No  Thur  Lunch     4
86       13.03  2.00    Male     No  Thur  Lunch     2
87       18.28  4.00    Male     No  Thur  Lunch     2
88       24.71  5.85    Male     No  Thur  Lunch     2
89       21.16  3.00    Male     No  Thur  Lunch     2
    total_bill   tip     sex smoker  day    time  size
90       28.97  3.00    Male    Yes  Fri  Dinner     2
91       22.49  3.50    Male     No  Fri  Dinner     2
92        5.75  1.00  Female    Yes  Fri  Dinner     2
93       16.32  4.30  Female    Yes  Fri  Dinner     2
94       22.75  3.25  Female     No  Fri  Dinner     2
95       40.17  4.73    Male    Yes  Fri  Dinner     4
96       27.28  4.00    Male    Yes  Fri  Dinner     2
97       12.03  1.50    Male    Yes  Fri  Dinner     2
98       21.01  3.00    Male    Yes  Fri  Dinner     2
99       12.46  1.50    Male     No  Fri  Dinner     2
     total_bill   tip     sex smoker  day    time  size
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
102       44.30  2.50  Female    Yes  Sat  Dinner     3
103       22.42  3.48  Female    Yes  Sat  Dinner     2
104       20.92  4.08  Female     No  Sat  Dinner     2
105       15.36  1.64    Male    Yes  Sat  Dinner     2
106       20.49  4.06    Male    Yes  Sat  Dinner     2
107       25.21  4.29    Male    Yes  Sat  Dinner     2
108       18.24  3.76    Male     No  Sat  Dinner     2
109       14.31  4.00  Female    Yes  Sat  Dinner     2
     total_bill   tip     sex smoker   day    time  size
110       14.00  3.00    Male     No   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
112       38.07  4.00    Male     No   Sun  Dinner     3
113       23.95  2.55    Male     No   Sun  Dinner     2
114       25.71  4.00  Female     No   Sun  Dinner     3
115       17.31  3.50  Female     No   Sun  Dinner     2
116       29.93  5.07    Male     No   Sun  Dinner     4
117       10.65  1.50  Female     No  Thur   Lunch     2
118       12.43  1.80  Female     No  Thur   Lunch     2
119       24.08  2.92  Female     No  Thur   Lunch     4
     total_bill   tip     sex smoker   day   time  size
120       11.69  2.31    Male     No  Thur  Lunch     2
121       13.42  1.68  Female     No  Thur  Lunch     2
122       14.26  2.50    Male     No  Thur  Lunch     2
123       15.95  2.00    Male     No  Thur  Lunch     2
124       12.48  2.52  Female     No  Thur  Lunch     2
125       29.80  4.20  Female     No  Thur  Lunch     6
126        8.52  1.48    Male     No  Thur  Lunch     2
127       14.52  2.00  Female     No  Thur  Lunch     2
128       11.38  2.00  Female     No  Thur  Lunch     2
129       22.82  2.18    Male     No  Thur  Lunch     3
     total_bill   tip     sex smoker   day   time  size
130       19.08  1.50    Male     No  Thur  Lunch     2
131       20.27  2.83  Female     No  Thur  Lunch     2
132       11.17  1.50  Female     No  Thur  Lunch     2
133       12.26  2.00  Female     No  Thur  Lunch     2
134       18.26  3.25  Female     No  Thur  Lunch     2
135        8.51  1.25  Female     No  Thur  Lunch     2
136       10.33  2.00  Female     No  Thur  Lunch     2
137       14.15  2.00  Female     No  Thur  Lunch     2
138       16.00  2.00    Male    Yes  Thur  Lunch     2
139       13.16  2.75  Female     No  Thur  Lunch     2
     total_bill   tip     sex smoker   day   time  size
140       17.47  3.50  Female     No  Thur  Lunch     2
141       34.30  6.70    Male     No  Thur  Lunch     6
142       41.19  5.00    Male     No  Thur  Lunch     5
143       27.05  5.00  Female     No  Thur  Lunch     6
144       16.43  2.30  Female     No  Thur  Lunch     2
145        8.35  1.50  Female     No  Thur  Lunch     2
146       18.64  1.36  Female     No  Thur  Lunch     3
147       11.87  1.63  Female     No  Thur  Lunch     2
148        9.78  1.73    Male     No  Thur  Lunch     2
149        7.51  2.00    Male     No  Thur  Lunch     2
     total_bill   tip     sex smoker  day    time  size
150       14.07  2.50    Male     No  Sun  Dinner     2
151       13.13  2.00    Male     No  Sun  Dinner     2
152       17.26  2.74    Male     No  Sun  Dinner     3
153       24.55  2.00    Male     No  Sun  Dinner     4
154       19.77  2.00    Male     No  Sun  Dinner     4
155       29.85  5.14  Female     No  Sun  Dinner     5
156       48.17  5.00    Male     No  Sun  Dinner     6
157       25.00  3.75  Female     No  Sun  Dinner     4
158       13.39  2.61  Female     No  Sun  Dinner     2
159       16.49  2.00    Male     No  Sun  Dinner     4
     total_bill   tip     sex smoker  day    time  size
160       21.50  3.50    Male     No  Sun  Dinner     4
161       12.66  2.50    Male     No  Sun  Dinner     2
162       16.21  2.00  Female     No  Sun  Dinner     3
163       13.81  2.00    Male     No  Sun  Dinner     2
164       17.51  3.00  Female    Yes  Sun  Dinner     2
165       24.52  3.48    Male     No  Sun  Dinner     3
166       20.76  2.24    Male     No  Sun  Dinner     2
167       31.71  4.50    Male     No  Sun  Dinner     4
168       10.59  1.61  Female    Yes  Sat  Dinner     2
169       10.63  2.00  Female    Yes  Sat  Dinner     2
     total_bill    tip     sex smoker  day    time  size
170       50.81  10.00    Male    Yes  Sat  Dinner     3
171       15.81   3.16    Male    Yes  Sat  Dinner     2
172        7.25   5.15    Male    Yes  Sun  Dinner     2
173       31.85   3.18    Male    Yes  Sun  Dinner     2
174       16.82   4.00    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
176       17.89   2.00    Male    Yes  Sun  Dinner     2
177       14.48   2.00    Male    Yes  Sun  Dinner     2
178        9.60   4.00  Female    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
     total_bill   tip     sex smoker  day    time  size
180       34.65  3.68    Male    Yes  Sun  Dinner     4
181       23.33  5.65    Male    Yes  Sun  Dinner     2
182       45.35  3.50    Male    Yes  Sun  Dinner     3
183       23.17  6.50    Male    Yes  Sun  Dinner     4
184       40.55  3.00    Male    Yes  Sun  Dinner     2
185       20.69  5.00    Male     No  Sun  Dinner     5
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
     total_bill   tip     sex smoker   day    time  size
190       15.69  1.50    Male    Yes   Sun  Dinner     2
191       19.81  4.19  Female    Yes  Thur   Lunch     2
192       28.44  2.56    Male    Yes  Thur   Lunch     2
193       15.48  2.02    Male    Yes  Thur   Lunch     2
194       16.58  4.00    Male    Yes  Thur   Lunch     2
195        7.56  1.44    Male     No  Thur   Lunch     2
196       10.34  2.00    Male    Yes  Thur   Lunch     2
197       43.11  5.00  Female    Yes  Thur   Lunch     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2
199       13.51  2.00    Male    Yes  Thur   Lunch     2
     total_bill   tip     sex smoker   day    time  size
200       18.71  4.00    Male    Yes  Thur   Lunch     3
201       12.74  2.01  Female    Yes  Thur   Lunch     2
202       13.00  2.00  Female    Yes  Thur   Lunch     2
203       16.40  2.50  Female    Yes  Thur   Lunch     2
204       20.53  4.00    Male    Yes  Thur   Lunch     4
205       16.47  3.23  Female    Yes  Thur   Lunch     3
206       26.59  3.41    Male    Yes   Sat  Dinner     3
207       38.73  3.00    Male    Yes   Sat  Dinner     4
208       24.27  2.03    Male    Yes   Sat  Dinner     2
209       12.76  2.23  Female    Yes   Sat  Dinner     2
     total_bill   tip     sex smoker  day    time  size
210       30.06  2.00    Male    Yes  Sat  Dinner     3
211       25.89  5.16    Male    Yes  Sat  Dinner     4
212       48.33  9.00    Male     No  Sat  Dinner     4
213       13.27  2.50  Female    Yes  Sat  Dinner     2
214       28.17  6.50  Female    Yes  Sat  Dinner     3
215       12.90  1.10  Female    Yes  Sat  Dinner     2
216       28.15  3.00    Male    Yes  Sat  Dinner     5
217       11.59  1.50    Male    Yes  Sat  Dinner     2
218        7.74  1.44    Male    Yes  Sat  Dinner     2
219       30.14  3.09  Female    Yes  Sat  Dinner     4
     total_bill   tip     sex smoker  day    time  size
220       12.16  2.20    Male    Yes  Fri   Lunch     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
222        8.58  1.92    Male    Yes  Fri   Lunch     1
223       15.98  3.00  Female     No  Fri   Lunch     3
224       13.42  1.58    Male    Yes  Fri   Lunch     2
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2
227       20.45  3.00    Male     No  Sat  Dinner     4
228       13.28  2.72    Male     No  Sat  Dinner     2
229       22.12  2.88  Female    Yes  Sat  Dinner     2
     total_bill   tip     sex smoker  day    time  size
230       24.01  2.00    Male    Yes  Sat  Dinner     4
231       15.69  3.00    Male    Yes  Sat  Dinner     3
232       11.61  3.39    Male     No  Sat  Dinner     2
233       10.77  1.47    Male     No  Sat  Dinner     2
234       15.53  3.00    Male    Yes  Sat  Dinner     2
235       10.07  1.25    Male     No  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
     total_bill   tip     sex smoker   day    time  size
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [234]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        10 non-null     int64
 1   name               10 non-null     str
 2   department         10 non-null     str
 3   age                9 non-null      float64
 4   salary             9 non-null      float64
 5   experience         10 non-null     int64
 6   city               10 non-null     str
 7   joining_date       10 non-null     datetime64[us]
 8   performance_score  9 non-null      float64
 9   salary_1           9 non-null      float64
 10  salary_in_lakhs    9 non-null      float64
 11  senior             10 non-null     bool
 12  salary_level       10 non-null     str
 13  age_cat            10 non-null     str
 14  joining_yearly     10 non-null     int32
 15  month              10 non-null     int32
 16  salary_rank        9 non-null      float64
 17  avg_salary         10 non-null     float64
dtypes: bool(1), datetime64[us](1), float64(7), int32(2), int64(2), str(5)
memory usage: 3.7 KB

In [235]:
df["salary"] = pd.to_numeric(
    df["age"],
    downcast= 'float'
)

In [236]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        10 non-null     int64
 1   name               10 non-null     str
 2   department         10 non-null     str
 3   age                9 non-null      float64
 4   salary             9 non-null      float32
 5   experience         10 non-null     int64
 6   city               10 non-null     str
 7   joining_date       10 non-null     datetime64[us]
 8   performance_score  9 non-null      float64
 9   salary_1           9 non-null      float64
 10  salary_in_lakhs    9 non-null      float64
 11  senior             10 non-null     bool
 12  salary_level       10 non-null     str
 13  age_cat            10 non-null     str
 14  joining_yearly     10 non-null     int32
 15  month              10 non-null     int32
 16  salary_rank        9 non-null      float64
 17  avg_salary         10 non-null     float64
dtypes: bool(1), datetime64[us](1), float32(1), float64(6), int32(2), int64(2), str(5)
memory usage: 3.6 KB

### Find the top 2 highest-paid employees from each department, but only consider employees with at least 5 years of experience.

In [246]:
df

,employee_id,name,department,age,salary,experience,city,joining_date,performance_score
0,101,Alice,IT,25.0,60000.0,2,Delhi,2022-01-15,8.5
1,102,Bob,HR,32.0,52000.0,8,Mumbai,2018-03-10,7.2
2,103,Charlie,IT,28.0,75000.0,4,Delhi,2021-06-20,9.1
3,104,David,Finance,45.0,90000.0,18,Pune,2006-07-01,8.8
4,105,Eva,HR,29.0,58000.0,5,Mumbai,2020-02-15,6.9
5,106,Frank,IT,35.0,72000.0,10,Delhi,2016-11-10,9.5
6,107,Grace,Finance,41.0,85000.0,15,Pune,2009-05-20,7.8
7,108,Henry,IT,26.0,NaN,3,Delhi,2023-01-05,8.2
8,109,Ivy,HR,NaN,62000.0,6,Mumbai,2019-08-12,NaN
9,110,Jack,Finance,38.0,95000.0,12,Delhi,2014-04-25,9.0

In [256]:
df[df["experience"] >5 ].sort_values("salary",ascending=False).groupby("department")

In [ ]:
pd.Da