# let's revive Pandas!!!

In [4]:
!conda install pandas -y

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda3

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    intel-openmp-2025.0.0      |    h06a4308_1172        19.3 MB
    libhwloc-2.12.1            |default_hf1bbc79_1000         2.4 MB
    mkl-2025.0.0               |     h6d8faa4_942       113.4 MB
    mkl-service-2.7.2          |  py313h365c7f6_0          74 KB
    mkl_fft-2.2.0              |  py313h44c8d7b_0         178 KB
    mkl_random-1.4.1           |  py313h86c3e14_0         389 KB
    numpy-2.5.1                |  py313h4c24699_0          19 KB
    numpy-base-2.5.1           |  py313h00548fb_0         8.2 MB
    pandas-3.0.5               |  py313h86c3e14_0        14.1 MB
    tbb-2022.3.0               |       h698db13_0         181 KB
    tbb-devel-2022.3.0         |       h698db13_0         1.1 MB
    ------------------------------------------------------------
                                           Total:       159.3 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  intel-openmp       pkgs/main/linux-64::intel-openmp-2025.0.0-h06a4308_1172
  libhwloc           pkgs/main/linux-64::libhwloc-2.12.1-default_hf1bbc79_1000
  mkl                pkgs/main/linux-64::mkl-2025.0.0-h6d8faa4_942
  mkl-service        pkgs/main/linux-64::mkl-service-2.7.2-py313h365c7f6_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-2.2.0-py313h44c8d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.4.1-py313h86c3e14_0
  numpy              pkgs/main/linux-64::numpy-2.5.1-py313h4c24699_0
  numpy-base         pkgs/main/linux-64::numpy-base-2.5.1-py313h00548fb_0
  pandas             pkgs/main/linux-64::pandas-3.0.5-py313h86c3e14_0
  tbb                pkgs/main/linux-64::tbb-2022.3.0-h698db13_0
  tbb-devel          pkgs/main/linux-64::tbb-devel-2022.3.0-h698db13_0



Downloading and Extracting Packages:
mkl-2025.0.0         | 113.4 MB  |                                       |   0%
intel-openmp-2025.0. | 19.3 MB   |                                       |   0%

pandas-3.0.5         | 14.1 MB   |                                       |   0%


numpy-base-2.5.1     | 8.2 MB    |                                       |   0%



libhwloc-2.12.1      | 2.4 MB    |                                       |   0%




tbb-devel-2022.3.0   | 1.1 MB    |                                       |   0%





mkl_random-1.4.1     | 389 KB    |                                       |   0%






tbb-2022.3.0         | 181 KB    |                                       |   0%







mkl_fft-2.2.0        | 178 KB    |                                       |   0%








mkl-service-2.7.2    | 74 KB     |                                       |   0%









numpy-2.5.1          | 19 KB     |                                       |   0%










blas-1.0             | 6 KB      |                                       |   0%

pandas-3.0.5         | 14.1 MB   |                                       |   0%

pandas-3.0.5         | 14.1 MB   | ####3                                 |  12%

pandas-3.0.5         | 14.1 MB   | ##########                            |  27%

pandas-3.0.5         | 14.1 MB   | ###############8                      |  43%

pandas-3.0.5         | 14.1 MB   | #####################8                |  59%

pandas-3.0.5         | 14.1 MB   | ############################2         |  76%

pandas-3.0.5         | 14.1 MB   | ###################################3  |  96%

pandas-3.0.5         | 14.1 MB   | ##################################### | 100%




tbb-devel-2022.3.0   | 1.1 MB    | 5                                     |   1%




tbb-devel-2022.3.0   | 1.1 MB    | ##################################### | 100%





mkl_random-1.4.1     | 389 KB    | #5                                    |   4%





mkl_random-1.4.1     | 389 KB    | ##################################### | 100%





mkl_random-1.4.1     | 389 KB    | ##################################### | 100%






tbb-2022.3.0         | 181 KB    | ###2                                  |   9%






tbb-2022.3.0         | 181 KB    | ##################################### | 100%






tbb-2022.3.0         | 181 KB    | ##################################### | 100%







mkl_fft-2.2.0        | 178 KB    | ###3                                  |   9%







mkl_fft-2.2.0        | 178 KB    | ##################################### | 100%








mkl-service-2.7.2    | 74 KB     | ########                              |  22%








mkl-service-2.7.2    | 74 KB     | ##################################### | 100%







mkl_fft-2.2.0        | 178 KB    | ##################################### | 100%








mkl-service-2.7.2    | 74 KB     | ##################################### | 100%









numpy-2.5.1          | 19 KB     | ##############################6       |  83%









numpy-2.5.1          | 19 KB     | ##################################### | 100%









numpy-2.5.1          | 19 KB     | ##################################### | 100%










blas-1.0             | 6 KB      | ##################################### | 100%










blas-1.0             | 6 KB      | ##################################### | 100%










blas-1.0             | 6 KB      | ##################################### | 100%




tbb-devel-2022.3.0   | 1.1 MB    | ##################################### | 100%




tbb-devel-2022.3.0   | 1.1 MB    | ##################################### | 100%
intel-openmp-2025.0. | 19.3 MB   |                                       |   0%
intel-openmp-2025.0. | 19.3 MB   | ####3                                 |  12%
intel-openmp-2025.0. | 19.3 MB   | ##########2                           |  28%
intel-openmp-2025.0. | 19.3 MB   | #################1                    |  46%

pandas-3.0.5         | 14.1 MB   | ##################################### | 100%
intel-openmp-2025.0. | 19.3 MB   | #######################2              |  63%
intel-openmp-2025.0. | 19.3 MB   | #############################3        |  79%
intel-openmp-2025.0. | 19.3 MB   | ###################################1  |  95%
intel-openmp-2025.0. | 19.3 MB   | ##################################### | 100%
intel-openmp-2025.0. | 19.3 MB   | ##################################### | 100%


numpy-base-2.5.1     | 8.2 MB    |                                       |   0%


numpy-base-2.5.1     | 8.2 MB    | #######3                              |  20%


numpy-base-2.5.1     | 8.2 MB    | ###################6                  |  53%


numpy-base-2.5.1     | 8.2 MB    | #################################2    |  90%


numpy-base-2.5.1     | 8.2 MB    | ##################################### | 100%


numpy-base-2.5.1     | 8.2 MB    | ##################################### | 100%



libhwloc-2.12.1      | 2.4 MB    | 2                                     |   1%



libhwloc-2.12.1      | 2.4 MB    | ############################8         |  78%



libhwloc-2.12.1      | 2.4 MB    | ##################################### | 100%






































































Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [5]:
import pandas as pd

data = {
    "name": ["Karan", "Sam", "John", "Lisa", "Aman", "Priya"],
    "age": [28, 24, 32, 29, 21, 35],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],
    "salary": [80000, 50000, 90000, 65000, 45000, 100000]
}

df = pd.DataFrame(data)

In [6]:
df

    name  age    city  salary
0  Karan   28   Delhi   80000
1    Sam   24  Mumbai   50000
2   John   32   Delhi   90000
3   Lisa   29    Pune   65000
4   Aman   21  Mumbai   45000
5  Priya   35   Delhi  100000

In [7]:
df["name"]

0    Karan
1      Sam
2     John
3     Lisa
4     Aman
5    Priya
Name: name, dtype: str

In [9]:
df[["name","salary"]]

    name  salary
0  Karan   80000
1    Sam   50000
2   John   90000
3   Lisa   65000
4   Aman   45000
5  Priya  100000

In [17]:
df[df["age"]>25]

    name  age   city  salary
0  Karan   28  Delhi   80000
2   John   32  Delhi   90000
3   Lisa   29   Pune   65000
5  Priya   35  Delhi  100000

In [24]:
df[(df["city"]=="Delhi") & (df["salary"]>80000)]

    name  age   city  salary
2   John   32  Delhi   90000
5  Priya   35  Delhi  100000

In [25]:
df.sort_values("salary")

    name  age    city  salary
4   Aman   21  Mumbai   45000
1    Sam   24  Mumbai   50000
3   Lisa   29    Pune   65000
0  Karan   28   Delhi   80000
2   John   32   Delhi   90000
5  Priya   35   Delhi  100000

In [40]:
df["salary_k"] = df["salary"]//1000
df

    name  age    city  salary  salary_k
0  Karan   28   Delhi   80000        80
1    Sam   24  Mumbai   50000        50
2   John   32   Delhi   90000        90
3   Lisa   29    Pune   65000        65
4   Aman   21  Mumbai   45000        45
5  Priya   35   Delhi  100000       100

In [33]:
df.value_counts("city")

city
Delhi     3
Mumbai    2
Pune      1
Name: count, dtype: int64

In [37]:
df.groupby("city")["salary"].mean()

city
Delhi     90000.0
Mumbai    47500.0
Pune      65000.0
Name: salary, dtype: float64

In [ ]:
df[df["city"].isin(["Delhi","Mumbai"])]

    name  age    city  salary  salary_k
0  Karan   28   Delhi   80000        80
1    Sam   24  Mumbai   50000        50
2   John   32   Delhi   90000        90
4   Aman   21  Mumbai   45000        45
5  Priya   35   Delhi  100000       100

In [43]:
df[(df["age"]>25)].isin(["Delhi","Mumbai"]).sort_values("salary")

    name    age   city  salary  salary_k
0  False  False   True   False     False
2  False  False   True   False     False
3  False  False  False   False     False
5  False  False   True   False     False

In [47]:
df[
    (df["age"]>25)&
    (df["city"].isin(["Delhi","Mumbai"]))

][["name","salary"]].sort_values("salary",ascending=False)

    name  salary
5  Priya  100000
2   John   90000
0  Karan   80000

## level2

In [ ]:
import pandas as pd

employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "name": ["Karan", "Sam", "John", "Lisa", "Aman", "Priya", "Raj", "Neha"],
    "department": ["AI", "Web", "AI", "HR", "Web", "AI", "HR", "Web"],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune", "Delhi"],

    "age": [28, 24, 32, 29, 21, 35, 31, 26],
    "salary": [80000, 50000, 90000, 65000, 45000, 100000, 70000, 60000]
})

In [57]:
employees[
    (employees["salary"]>80000 ) & employees["department"].isin(["AI"])          
          ][["name","salary","department"]].sort_values("salary",ascending=False)

    name  salary department
5  Priya  100000         AI
2   John   90000         AI

In [63]:
employees[["department"]].value_counts()

department
AI            3
Web           3
HR            2
Name: count, dtype: int64

In [81]:
employees.groupby("department")["salary"].mean()

department
AI     90000.000000
HR     67500.000000
Web    51666.666667
Name: salary, dtype: float64

In [90]:
employees.groupby("department")["salary"].agg(["count","min","max","mean"])

            count    min     max          mean
department
AI              3  80000  100000  90000.000000
HR              2  65000   70000  67500.000000
Web             3  45000   60000  51666.666667

In [93]:
def classify(salary):
    if salary  >= 80000:
        return "high"
    return "low"


employees["status"] = employees["salary"].apply(classify)

In [95]:
employees

   employee_id   name department    city  age  salary status
0            1  Karan         AI   Delhi   28   80000   high
1            2    Sam        Web  Mumbai   24   50000    low
2            3   John         AI   Delhi   32   90000   high
3            4   Lisa         HR    Pune   29   65000    low
4            5   Aman        Web  Mumbai   21   45000    low
5            6  Priya         AI   Delhi   35  100000   high
6            7    Raj         HR    Pune   31   70000    low
7            8   Neha        Web   Delhi   26   60000    low

In [96]:
def classify(age):
    if age  < 25:
        return "young"
    elif age >=25 and age < 30:
        return "Adult"
    else:
        return "old"


employees["age_group"] = employees["age"].apply(classify)

In [97]:
employees

   employee_id   name department    city  age  salary status age_group
0            1  Karan         AI   Delhi   28   80000   high     Adult
1            2    Sam        Web  Mumbai   24   50000    low     young
2            3   John         AI   Delhi   32   90000   high       old
3            4   Lisa         HR    Pune   29   65000    low     Adult
4            5   Aman        Web  Mumbai   21   45000    low     young
5            6  Priya         AI   Delhi   35  100000   high       old
6            7    Raj         HR    Pune   31   70000    low       old
7            8   Neha        Web   Delhi   26   60000    low     Adult

In [114]:
employees.groupby("department")["salary"].mean()> 60000

department
AI      True
HR      True
Web    False
Name: salary, dtype: bool

In [119]:
result = employees.groupby("department")["salary"].mean()

result

department
AI     90000.000000
HR     67500.000000
Web    51666.666667
Name: salary, dtype: float64

In [120]:
result[ result > 65000 ]

department
AI    90000.0
HR    67500.0
Name: salary, dtype: float64

In [121]:
locations = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6, 7],
    "office": ["A", "B", "A", "C", "B", "A", "C"],
    "manager": ["Raj", "Neha", "Raj", "Aman", "Neha", "Raj", "Aman"]
})

In [122]:
employees.merge(
    locations,
    on="employee_id",
    how="inner"
)

,employee_id,name,department,city,age,salary,status,age_group,office,manager
0,1,Karan,AI,Delhi,28,80000,high,Adult,A,Raj
1,2,Sam,Web,Mumbai,24,50000,low,young,B,Neha
2,3,John,AI,Delhi,32,90000,high,old,A,Raj
3,4,Lisa,HR,Pune,29,65000,low,Adult,C,Aman
4,5,Aman,Web,Mumbai,21,45000,low,young,B,Neha
5,6,Priya,AI,Delhi,35,100000,high,old,A,Raj
6,7,Raj,HR,Pune,31,70000,low,old,C,Aman

In [131]:
df= employees.merge(
    locations,
    on="employee_id",
    how="inner"
)

In [132]:
df

,employee_id,name,department,city,age,salary,status,age_group,office,manager
0,1,Karan,AI,Delhi,28,80000,high,Adult,A,Raj
1,2,Sam,Web,Mumbai,24,50000,low,young,B,Neha
2,3,John,AI,Delhi,32,90000,high,old,A,Raj
3,4,Lisa,HR,Pune,29,65000,low,Adult,C,Aman
4,5,Aman,Web,Mumbai,21,45000,low,young,B,Neha
5,6,Priya,AI,Delhi,35,100000,high,old,A,Raj
6,7,Raj,HR,Pune,31,70000,low,old,C,Aman

In [143]:
df[(df["department"] == "AI") & (df["office"] == "A")][["name","salary","office"]]

    name  salary office
0  Karan   80000      A
2   John   90000      A
5  Priya  100000      A

In [144]:
df

,employee_id,name,department,city,age,salary,status,age_group,office,manager
0,1,Karan,AI,Delhi,28,80000,high,Adult,A,Raj
1,2,Sam,Web,Mumbai,24,50000,low,young,B,Neha
2,3,John,AI,Delhi,32,90000,high,old,A,Raj
3,4,Lisa,HR,Pune,29,65000,low,Adult,C,Aman
4,5,Aman,Web,Mumbai,21,45000,low,young,B,Neha
5,6,Priya,AI,Delhi,35,100000,high,old,A,Raj
6,7,Raj,HR,Pune,31,70000,low,old,C,Aman

In [166]:
result  = df.groupby("department")["salary"].max()

In [167]:
df["max_salary"] = df.groupby("department")["salary"].transform("max")

In [168]:
df[df["salary"] == df["max_salary"]]

,employee_id,name,department,city,age,salary,status,age_group,office,manager,max_salary
1,2,Sam,Web,Mumbai,24,50000,low,young,B,Neha,50000
5,6,Priya,AI,Delhi,35,100000,high,old,A,Raj,100000
6,7,Raj,HR,Pune,31,70000,low,old,C,Aman,70000

## level 3



# 🔴 Pandas Level 3 — 10 Problems

Use this dataset:

```python
import pandas as pd

patients = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": [
        "Karan", "Sam", "John", "Lisa", "Aman",
        "Priya", "Raj", "Neha", "Alex", "Sara"
    ],
    "gender": [
        "M", "M", "M", "F", "M",
        "F", "M", "F", "M", "F"
    ],
    "age": [28, 45, 32, 29, 21, 35, 41, 26, 52, 38],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
        "Delhi", "Pune", "Delhi", "Mumbai", "Pune"
    ],
    "weight": [72, 85, 90, 60, 68, 75, 88, 55, 95, 70]
})
```

---

## 🟢 Problem 21 — Percentage

Find the **percentage of male patients**.

Expected output:

```text
male_percentage
---------------
?
```

### Think

```text
number of males
       ÷
total patients
       × 100
```

---

## 🟢 Problem 22 — Multiple conditions

Find patients who:

* are female
* age between **25 and 40**
* live in either Delhi or Pune

Return:

```text
name
age
city
```

Sort by age.

---

## 🟡 Problem 23 — GroupBy + count

Find the **number of patients of each gender in each city**.

Expected structure:

```text
city | gender | count
```

Think:

```text
city + gender
      ↓
groups
      ↓
count
```

---

## 🟡 Problem 24 — GroupBy + average

Find the **average weight of males and females**.

Expected:

```text
gender | average_weight
```

Round the answer to **1 decimal place**.

---

## 🟡 Problem 25 — Find the city with the most patients

Find which city has the **highest number of patients**.

Don't manually inspect the dataset.

Think:

```text
count patients by city
       ↓
sort/count maximum
       ↓
take top one
```

---

## 🟠 Problem 26 — Duplicate detection

Create this DataFrame:

```python
visits = pd.DataFrame({
    "patient_id": [1, 2, 3, 1, 4, 2, 5, 3],
    "doctor": ["A", "B", "A", "A", "C", "B", "D", "A"]
})
```

Find patients who appear **more than once**.

Expected:

```text
patient_id
1
2
3
```

### Important

Don't just use `duplicated()` blindly.

Try to understand:

```text
patient_id
   ↓
count occurrences
   ↓
keep count > 1
```

---

# 🟠 Problem 27 — Merge

Create:

```python
doctors = pd.DataFrame({
    "doctor_id": [101, 102, 103, 104],
    "doctor_name": ["Dr. Singh", "Dr. Sharma", "Dr. Khan", "Dr. Gupta"],
    "specialty": ["Cardiology", "Neurology", "Pediatrics", "Orthopedics"]
})

admissions = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6],
    "doctor_id": [101, 102, 101, 104, 103, 102]
})
```

Merge them so each admission shows:

```text
patient_id
doctor_name
specialty
```

---

# 🟠 Problem 28 — Merge + GroupBy

Using `admissions` and `doctors`:

Find the **number of patients handled by each doctor**.

Expected:

```text
doctor_name | patient_count
```

Think:

```text
merge
 ↓
groupby doctor
 ↓
count patients
```

---

# 🔴 Problem 29 — Find the second highest

Using:

```python
patients
```

Find the **second highest weight**.

Don't use:

```python
sorted(...)
```

Try to solve it using Pandas operations.

### Think:

```text
weight
 ↓
remove duplicates
 ↓
sort
 ↓
take second
```

---

# 🔴 Problem 30 — Mini LeetCode-style problem

This one is your final challenge.

### Question

Find the **city with the highest average patient weight**.

Return:

```text
city
average_weight
```

Round average weight to **2 decimal places**.

Sort highest → lowest.

Return only the **top city**.

Think:

```text
city
 ↓
groupby
 ↓
average weight
 ↓
sort descending
 ↓
first row
```

---

# 🧠 The goal of Level 3

I want you to start translating English → Pandas operations.

For example:

> "number of patients per city"

Your brain should start saying:

```text
"per city"
   ↓
groupby("city")

"number"
   ↓
count()
```

Or:

> "highest average weight by city"

Your brain should say:

```text
"by city"
   ↓
groupby

"average"
   ↓
mean

"highest"
   ↓
sort descending / max
```

That's the intuition we're trying to build.

### Start with **Problem 21**.

Don't worry if you get stuck. **Give me your attempt even if it's completely wrong.** That's actually more useful for learning than looking at the answer.

In [221]:
import pandas as pd

df = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": [
        "Karan", "Sam", "John", "Lisa", "Aman",
        "Priya", "Raj", "Neha", "Alex", "Sara"
    ],
    "gender": [
        "M", "M", "M", "F", "M",
        "F", "M", "F", "M", "F"
    ],
    "age": [28, 45, 32, 29, 21, 35, 41, 26, 52, 38],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
        "Delhi", "Pune", "Delhi", "Mumbai", "Pune"
    ],
    "weight": [72, 85, 90, 60, 68, 75, 88, 55, 95, 70]
})
df

   patient_id   name gender  age    city  weight
0           1  Karan      M   28   Delhi      72
1           2    Sam      M   45  Mumbai      85
2           3   John      M   32   Delhi      90
3           4   Lisa      F   29    Pune      60
4           5   Aman      M   21  Mumbai      68
5           6  Priya      F   35   Delhi      75
6           7    Raj      M   41    Pune      88
7           8   Neha      F   26   Delhi      55
8           9   Alex      M   52  Mumbai      95
9          10   Sara      F   38    Pune      70

In [193]:
male_patient_count= df[df["gender" ]== "M" ]["name"].agg("count")
total_pat = df[["name"]]["name"].agg("count")
percent_male = (male_patient_count/total_pat) *100
print(percent_male)

60.0

🟢 Problem 22 — Multiple conditions

Find patients who:

are female
age between 25 and 40
live in either Delhi or Pune

Return:

name
age
city

Sort by age.

In [206]:
age_sorted_df=df[df["gender"]=="F"][["age","name","city"]].sort_values("age")
age_sorted_df[
    (age_sorted_df["age"]>25) & 
    (age_sorted_df["age"]<40) &
     (age_sorted_df["city"].isin(["Delhi","Pune"])) ]

   age   name   city
7   26   Neha  Delhi
3   29   Lisa   Pune
5   35  Priya  Delhi
9   38   Sara   Pune

🟡 Problem 23 — GroupBy + count

Find the number of patients of each gender in each city.

Expected structure:

city | gender | count

Think:

city + gender
      ↓
groups
      ↓
count

In [323]:
df.groupby(["city", "gender"]).size()

city    gender
Delhi   F         2
        M         2
Mumbai  M         3
Pune    F         2
        M         1
dtype: int64

In [267]:
df[["gender","city"]].groupby("city").value_counts()

city    gender
Delhi   M         2
        F         2
Mumbai  M         3
Pune    F         2
        M         1
Name: count, dtype: int64

🟡 Problem 24 — GroupBy + average

Find the average weight of males and females.

Expected:

gender | average_weight

Round the answer to 1 decimal place.

In [324]:
df.groupby("gender")["weight"].mean().round(1)

gender
F    65.0
M    83.0
Name: weight, dtype: float64

In [277]:
df[["gender","weight"]].groupby("gender").agg("mean")

        weight
gender
F         65.0
M         83.0

In [280]:
df[["gender","weight"]].sort_values("gender")

  gender  weight
3      F      60
5      F      75
7      F      55
9      F      70
0      M      72
1      M      85
2      M      90
4      M      68
6      M      88
8      M      95

Problem 25 — Find the city with the most patients

Find which city has the highest number of patients.

Don't manually inspect the dataset.

Think:

count patients by city
       ↓
sort/count maximum
       ↓
take top one

In [327]:
df

   patient_id   name gender  age    city  weight  count
0           1  Karan      M   28   Delhi      72    NaN
1           2    Sam      M   45  Mumbai      85    NaN
2           3   John      M   32   Delhi      90    NaN
3           4   Lisa      F   29    Pune      60    NaN
4           5   Aman      M   21  Mumbai      68    NaN
5           6  Priya      F   35   Delhi      75    NaN
6           7    Raj      M   41    Pune      88    NaN
7           8   Neha      F   26   Delhi      55    NaN
8           9   Alex      M   52  Mumbai      95    NaN
9          10   Sara      F   38    Pune      70    NaN

In [338]:
df.groupby("city")["patient_id"].agg("count").sort_values(ascending=False).head(1)

city
Delhi    4
Name: patient_id, dtype: int64

In [337]:
df.groupby("city")["patient_id"].count().sort_values(ascending=False).head(1)

city
Delhi    4
Name: patient_id, dtype: int64

🟠 Problem 26 — Duplicate detection

Create this DataFrame:

visits = pd.DataFrame({
    "patient_id": [1, 2, 3, 1, 4, 2, 5, 3],
    "doctor": ["A", "B", "A", "A", "C", "B", "D", "A"]
})

Find patients who appear more than once.

Expected:

patient_id
1
2
3
Important

Don't just use duplicated() blindly.

Try to understand:

patient_id
   ↓
count occurrences
   ↓
keep count > 1

In [299]:
visits = pd.DataFrame({
    "patient_id": [1, 2, 3, 1, 4, 2, 5, 3],
    "doctor": ["A", "B", "A", "A", "C", "B", "D", "A"]
})

In [339]:
counts = visits["patient_id"].value_counts()

In [340]:
counts[counts >1]

patient_id
1    2
2    2
3    2
Name: count, dtype: int64

In [310]:
doctors = pd.DataFrame({
    "doctor_id": [101, 102, 103, 104],
    "doctor_name": ["Dr. Singh", "Dr. Sharma", "Dr. Khan", "Dr. Gupta"],
    "specialty": ["Cardiology", "Neurology", "Pediatrics", "Orthopedics"]
})

admissions = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5, 6],
    "doctor_id": [101, 102, 101, 104, 103, 102]
})

In [313]:
merge_df=doctors.merge(
    admissions,
    on='doctor_id',
    how = 'inner'
)

🟠 Problem 28 — Merge + GroupBy

Using admissions and doctors:

Find the number of patients handled by each doctor.

Expected:

doctor_name | patient_count

Think:

merge
 ↓
groupby doctor
 ↓
count patients

In [341]:
merge_df

   doctor_id doctor_name    specialty  patient_id
0        101   Dr. Singh   Cardiology           1
1        101   Dr. Singh   Cardiology           3
2        102  Dr. Sharma    Neurology           2
3        102  Dr. Sharma    Neurology           6
4        103    Dr. Khan   Pediatrics           5
5        104   Dr. Gupta  Orthopedics           4

In [322]:
merge_df[["doctor_name"]].groupby("doctor_name").value_counts()

doctor_name
Dr. Gupta     1
Dr. Khan      1
Dr. Sharma    2
Dr. Singh     2
Name: count, dtype: int64

In [342]:
merge_df.groupby("doctor_name")["patient_id"].count()

doctor_name
Dr. Gupta     1
Dr. Khan      1
Dr. Sharma    2
Dr. Singh     2
Name: patient_id, dtype: int64

🔴 Problem 29 — Find the second highest

Using:

patients

Find the second highest weight.

Don't use:

sorted(...)

Try to solve it using Pandas operations.

Think:
weight
 ↓
remove duplicates
 ↓
sort
 ↓
take second

In [343]:
df

   patient_id   name gender  age    city  weight  count
0           1  Karan      M   28   Delhi      72    NaN
1           2    Sam      M   45  Mumbai      85    NaN
2           3   John      M   32   Delhi      90    NaN
3           4   Lisa      F   29    Pune      60    NaN
4           5   Aman      M   21  Mumbai      68    NaN
5           6  Priya      F   35   Delhi      75    NaN
6           7    Raj      M   41    Pune      88    NaN
7           8   Neha      F   26   Delhi      55    NaN
8           9   Alex      M   52  Mumbai      95    NaN
9          10   Sara      F   38    Pune      70    NaN

In [353]:
df["weight"].sort_values(ascending=False).head(2)

8    95
2    90
Name: weight, dtype: int64

In [357]:
df["weight"].drop_duplicates().sort_values(ascending=False).head(2)

8    95
2    90
Name: weight, dtype: int64

In [358]:
second_highest = df["weight"].drop_duplicates().sort_values(ascending=False).iloc[1]

In [359]:
print(second_highest)

90

🔴 Problem 30 — Mini LeetCode-style problem

This one is your final challenge.

Question

Find the city with the highest average patient weight.

Return:

city
average_weight

Round average weight to 2 decimal places.

Sort highest → lowest.

Return only the top city.

Think:

city
 ↓
groupby
 ↓
average weight
 ↓
sort descending
 ↓
first row

In [361]:
df

   patient_id   name gender  age    city  weight  count
0           1  Karan      M   28   Delhi      72    NaN
1           2    Sam      M   45  Mumbai      85    NaN
2           3   John      M   32   Delhi      90    NaN
3           4   Lisa      F   29    Pune      60    NaN
4           5   Aman      M   21  Mumbai      68    NaN
5           6  Priya      F   35   Delhi      75    NaN
6           7    Raj      M   41    Pune      88    NaN
7           8   Neha      F   26   Delhi      55    NaN
8           9   Alex      M   52  Mumbai      95    NaN
9          10   Sara      F   38    Pune      70    NaN

In [378]:
df.groupby("city")["weight"].mean().sort_values(ascending=False).round(2).head(1)

city
Mumbai    82.67
Name: weight, dtype: float64

# top 30  pandas

### How do you create a DataFrame from a dictionary, a list of lists, and a CSV file?

In [3]:
import pandas as pd



df = pd.DataFrame({
    "name": ["karan","rohan","alex","sam"],
    "age":[1,2,3,4]
                   })

In [4]:
df

    name  age
0  karan    1
1  rohan    2
2   alex    3
3    sam    4

In [39]:
df = pd.read_csv("tips.csv")

In [12]:
df = pd.DataFrame([["karna","mkaak"],["sadad"]])

In [13]:
df

       0      1
0  karna  mkaak
1  sadad    NaN

### What's the difference between loc[] and iloc[]?

In pandas, loc and iloc are both used to select data from a DataFrame, but they differ in how they identify rows and columns.

Feature	                     loc	                    iloc
Selection type	           Label-based        	    Integer position-based
Uses	                   Row/column label         Row/column index positions
End index in slicing	   Included             	Excluded

In [22]:
df

df.loc[[0,1]]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [27]:
df.iloc[0:3]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

### How do you check for and count missing values in a DataFrame?

In [28]:
df.isnull().any()

total_bill    False
tip           False
sex           False
smoker        False
day           False
time          False
size          False
dtype: bool

In [29]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [30]:
df.isnull().mean()*100

total_bill    0.0
tip           0.0
sex           0.0
smoker        0.0
day           0.0
time          0.0
size          0.0
dtype: float64

### Difference between df.copy() and df2 = df1



"df2 = df1 creates another reference to the same DataFrame, so changes made through df2 will affect df1. df2 = df1.copy() creates an independent copy, so modifications to df2 don't affect the original DataFrame."

In [31]:
df1 = df

In [35]:
df
# df1

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [36]:
df["tip"] = 1

In [40]:
df2 = df.copy()

In [52]:
df2["tip"] = df2["tip"]*3

In [53]:
df2

     total_bill  tip     sex smoker   day    time  size
0         16.99    9  Female     No   Sun  Dinner     2
1         10.34    9    Male     No   Sun  Dinner     3
2         21.01    9    Male     No   Sun  Dinner     3
3         23.68    9    Male     No   Sun  Dinner     2
4         24.59    9  Female     No   Sun  Dinner     4
..          ...  ...     ...    ...   ...     ...   ...
239       29.03    9    Male     No   Sat  Dinner     3
240       27.18    9  Female    Yes   Sat  Dinner     2
241       22.67    9    Male    Yes   Sat  Dinner     2
242       17.82    9    Male     No   Sat  Dinner     2
243       18.78    9  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

1. df.query() vs Boolean Indexing

Both are used to filter rows in a DataFrame. The main difference is syntax and flexibility.

In [65]:
print(df.query("total_bill > 12 and day == 'Sun'"))
df[ ( df["total_bill"] > 12 ) & (df["day"] == "Sun") ]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[67 rows x 7 columns]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[67 rows x 7 columns]

#### How do you select rows where a column value is in a given list?

In [71]:
df.loc[~df["sex"].isin(["Male"])]

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

"map() is mainly used on a Series to transform individual elements. apply() is more general and can operate on a Series or DataFrame, including row-wise or column-wise operations. applymap() was traditionally used for element-wise operations across an entire DataFrame, but in modern Pandas it has been deprecated in favor of DataFrame.map()."

In [77]:
df["time"].map({
    "M": "Dinner",
    "F": "Lunch"
})

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
239    NaN
240    NaN
241    NaN
242    NaN
243    NaN
Name: time, Length: 244, dtype: str

### How do you use groupby() with multiple aggregation functions on different columns simultaneously?

In [ ]:
df.groupby(["Department", "City"]).agg({
    "Salary": "mean",
    "Age": "max"
})

### What's the difference between transform() and agg() in a groupby context?

"agg() reduces each group to one or more summary values, so the output is usually smaller than the original DataFrame. transform() performs a group-level calculation but returns a result with the same number of rows as the original data, broadcasting the group result back to each row. I use transform() when I need group statistics alongside the original rows."

In [ ]:
df.groupby("Department")["Salary"].agg("mean")

In [ ]:
df["Dept_Avg"] = df.groupby("Department")["Salary"].transform("mean")

How do you pivot a DataFrame using pivot_table() vs. pivot() — what's the key difference?


Both reshape a DataFrame from long format → wide format, but the key difference is:

pivot() requires unique combinations, while pivot_table() can handle duplicates by aggregating them.


| Department | City   | Salary |
| ---------- | ------ | -----: |
| IT         | Delhi  |     50 |
| IT         | Mumbai |     70 |
| HR         | Delhi  |     40 |
| HR         | Mumbai |     50 |



df.pivot(
    index="Department",
    columns="City",
    values="Salary"
)


| Department | Delhi | Mumbai |
| ---------- | ----: | -----: |
| HR         |    40 |     50 |
| IT         |    50 |     70 |

"pivot() reshapes the DataFrame but requires each index-column combination to be unique. If duplicate combinations exist, it raises an error. pivot_table() is more flexible because it can handle duplicates using an aggregation function such as mean, sum, or count. So I use pivot() for straightforward reshaping with unique combinations, and pivot_table() when aggregation may be required."

In [80]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 56.4 KB

In [88]:
df["total_bill_1"] = pd.to_numeric(df["total_bill"], downcast="float")